repos:
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: 
          - --max-line-length=120
          - --ignore=E203,W503,E501,E231,E226,E221,E222,E241,W291,F401,F541,F821,F841
          - --per-file-ignores=__init__.py:F401
        # Maak flake8 warnings, maar blokkeer commits niet
        stages: [manual]  # Alleen draaien bij handmatige check
        
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [--profile=black]